---

- name: install the latest version of texlive on Centos 8
  dnf:
    name: texlive
    state: latest
  async: 1000
  poll: 0
  register: dnf_sleeper

# Source: http://docs.ansible.com/ansible/latest/playbooks_async.html
- name: check on texlive installation
  async_status: jid={{ dnf_sleeper.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: "{{ tex_live_retries }}"